In [1]:
import torch

In [2]:
v = torch.tensor([1,2,3,4,5,6])

In [3]:
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [4]:
v[0]

tensor(1)

In [5]:
v[1]

tensor(2)

In [6]:
v[1:4]

tensor([2, 3, 4])

In [7]:
print(v.dtype)

torch.int64


In [8]:
f = torch.FloatTensor([1,2,3,4,5])

In [9]:
print(f.dtype)

torch.float32


In [10]:
print(f)

tensor([1., 2., 3., 4., 5.])


In [11]:
print(f.size())

torch.Size([5])


In [12]:
v.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
v.view(4, 2)

RuntimeError: shape '[4, 2]' is invalid for input of size 6

In [15]:
v.view(3, -1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [16]:
import numpy as np

In [17]:
numpy_array = np.array([1,2,3,4])

In [18]:
type(numpy_array)

numpy.ndarray

In [19]:
tensor_1 = torch.from_numpy(numpy_array)

In [20]:
print(tensor_1)

tensor([1, 2, 3, 4])


In [21]:
print(tensor_1.dtype)

torch.int64


In [22]:
numpy_1 = tensor_1.numpy()

In [23]:
print(numpy_1)

[1 2 3 4]


In [24]:
print(type(numpy_1))

<class 'numpy.ndarray'>
