In [1]:
import torch

In [2]:
one = torch.tensor([5,6,7])

In [3]:
two = torch.tensor([1,2,3])

In [4]:
sum = one + two 

In [5]:
print(sum)

tensor([ 6,  8, 10])


In [6]:
mult = one * two

In [7]:
print(mult)

tensor([ 5, 12, 21])


In [8]:
one + 5

tensor([10, 11, 12])

In [9]:
sub = one - two

In [10]:
print(sub)

tensor([4, 4, 4])


In [11]:
dot_op = torch.dot(one, two)

In [12]:
print(dot_op)

tensor(38)


In [14]:
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])