In [1]:
import torch

In [2]:
#Create Multi-D Tensors

In [3]:
m1 = torch.tensor([1,2,3,4,5,6,7,8])

In [4]:
print(m1)

tensor([1, 2, 3, 4, 5, 6, 7, 8])


In [5]:
m1 = m1.view(2, -1)

In [6]:
m1

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [7]:
m2 = torch.randn(2, 3)

In [8]:
print(m2)

tensor([[ 0.9468, -0.1854,  0.9114],
        [-0.6039, -0.0114,  1.3672]])


In [9]:
m3 = torch.arange(0, 8)

In [10]:
m3

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
m3 = m3.view(2, -1)

In [12]:
print(m3)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [13]:
m1 = torch.tensor([1,2,3,4])

In [15]:
m1 = m1.view(2, 2)

In [16]:
m2  = torch.tensor([1,2,3,4])

In [17]:
m2 = m2.view(2,2)

In [18]:
print(m1)

tensor([[1, 2],
        [3, 4]])


In [19]:
print(m2)

tensor([[1, 2],
        [3, 4]])


In [20]:
m1 * m2

tensor([[ 1,  4],
        [ 9, 16]])

In [21]:
torch.mul(m1,m2)

tensor([[ 1,  4],
        [ 9, 16]])

In [22]:
torch.matmul(m1, m2)

tensor([[ 7, 10],
        [15, 22]])

In [23]:
m1

tensor([[1, 2],
        [3, 4]])

In [24]:
m1[0,0]

tensor(1)

In [25]:
m1[0,1]

tensor(2)

In [26]:
m1[1,0]

tensor(3)

In [27]:
m1[1,1]

tensor(4)